version: '3.8'

services:
  tcp-server:
    build: .
    container_name: tcp_server_container
    ports:
      - "5060:5060"
      - "5061:5061"
      - "5062:5062"
    restart: unless-stopped
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
